### ISSUE TITLE
Problems to read the inputs from USR-IO88

### ISSUE THREAD

**Issue by dadante** [estbeetoo/node-red-contrib-usriot#1]
This board have a 8 digital input (from 12v to 36v) and 8 output (8 relay 250v 10A).
With this application I have the possibility to read the coil status only if I press the virtual button.
Is it possible to read the status of the digital inputs?

**Comment by aborovsky** [comment]
Hi, @dadante!
It was completely long ago, when i was developing this driver :)
Can't say for sure.
Do you able to setup remote access to usriot device port for me?
I'll do investigation.
Please, let's continue a dialog in private through email: aborovsky@beetoo.me.
